---
- name: Ansible ec2 termination
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - /etc/ansible/vars/vars.yaml

  vars:
    instance_name: HAProxy
    instance_name1: app-server1
    instance_name2: app-server2
    wait: yes
    region: eu-west-2

  tasks:
    - name: Terminating EC2 instances
      ec2_instance:
        state: absent
        name: "{{ item }}"
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
      delegate_to: localhost
      loop:
        - "{{ instance_name }}"
        - "{{ instance_name1 }}"
        - "{{ instance_name2 }}"

    - name: cleanup security group for the instance
      ec2_group:
        name: "{{ security_group }}"
        description: security-group-test
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        state: absent
      delegate_to: localhost
